version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "80:80"
      - "3002:3002"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    expose:
      - "3002"
    volumes:
      - ./db.json:/app/db.json
      - ./public:/app/public
