version: '3.8'
services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "443:443"
    volumes:
      - /etc/letsencrypt/live/jerkcloud.ru/fullchain.pem:/etc/letsencrypt/live/jerkcloud.ru/fullchain.pem:ro
      - /etc/letsencrypt/live/jerkcloud.ru/privkey.pem:/etc/letsencrypt/live/jerkcloud.ru/privkey.pem:ro
    depends_on:
      - backend
    networks:
      - my_network
  backend:
    build:
      context: .
      dockerfile: Dockerfile.back
    ports:
      - "3002:3002"
    networks:
      - my_network
    volumes:
      - ./db.json:/app/db.json
      - ./public:/app/public

networks:
  my_network:
    driver: bridge
